-- ============================================================
-- 공실뉴스 뉴스기사 DB 스키마
-- Supabase SQL Editor에 붙여넣고 Run 하세요
-- ============================================================

-- ① articles (기사 본문)
CREATE TABLE IF NOT EXISTS public.articles (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id       uuid REFERENCES auth.users(id) ON DELETE SET NULL,

    -- 상태 / 형태
    status          text NOT NULL DEFAULT 'draft',      -- draft | pending | published | hidden
    article_type    text NOT NULL DEFAULT 'normal',     -- normal | card | gallery

    -- 섹션
    section1        text,
    section2        text,
    section3        text,

    -- 기자 정보
    reporter_name   text,
    reporter_email  text,

    -- 제목
    title           text NOT NULL DEFAULT '',
    subtitle        text,

    -- 본문 (형태별)
    content         text,               -- 일반뉴스 HTML (Summernote)
    card_text_above text,               -- 카드뉴스 슬라이더 위 글
    card_text_below text,               -- 카드뉴스 슬라이더 아래 글
    gallery_title   text,               -- 갤러리 모드 타이틀

    -- 미디어 대표
    rep_media_id    bigint,             -- article_media.id 참조 (나중에 FK 추가)

    -- 키워드 / 노출
    keywords        text,               -- '#강남 #부동산' 형식
    expose_at       timestamptz DEFAULT now(),

    -- 위치
    lat             float8,
    lng             float8,

    -- 통계
    view_count      int NOT NULL DEFAULT 0,

    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ② article_media (첨부 미디어)
CREATE TABLE IF NOT EXISTS public.article_media (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id          bigint NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
    media_type          text NOT NULL DEFAULT 'image',   -- image | youtube | file
    url                 text NOT NULL,                   -- Storage URL 또는 YouTube embed URL
    caption             text,
    is_representative   boolean NOT NULL DEFAULT false,
    sort_order          int NOT NULL DEFAULT 0,
    created_at          timestamptz NOT NULL DEFAULT now()
);

-- ③ article_related (관련기사 연결)
CREATE TABLE IF NOT EXISTS public.article_related (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id          bigint NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
    related_article_id  bigint NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
    UNIQUE(article_id, related_article_id)
);

-- ── 인덱스 ──────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS articles_author_idx      ON public.articles (author_id);
CREATE INDEX IF NOT EXISTS articles_status_idx      ON public.articles (status);
CREATE INDEX IF NOT EXISTS articles_type_idx        ON public.articles (article_type);
CREATE INDEX IF NOT EXISTS articles_section1_idx    ON public.articles (section1);
CREATE INDEX IF NOT EXISTS articles_expose_idx      ON public.articles (expose_at DESC);
CREATE INDEX IF NOT EXISTS articles_created_idx     ON public.articles (created_at DESC);
CREATE INDEX IF NOT EXISTS article_media_art_idx    ON public.article_media (article_id);
CREATE INDEX IF NOT EXISTS article_related_art_idx  ON public.article_related (article_id);

-- ── updated_at 자동 갱신 트리거 ─────────────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_articles_updated_at ON public.articles;
CREATE TRIGGER trg_articles_updated_at
    BEFORE UPDATE ON public.articles
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── RLS (Row Level Security) ─────────────────────────────────
ALTER TABLE public.articles       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_media  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_related ENABLE ROW LEVEL SECURITY;

-- 👁 누구나 published 기사 읽기 가능
DROP POLICY IF EXISTS "articles_public_read" ON public.articles;
CREATE POLICY "articles_public_read"
    ON public.articles FOR SELECT
    USING (status = 'published');

-- ✏️ 로그인한 사용자는 자신의 기사 수정/삭제 가능
DROP POLICY IF EXISTS "articles_owner_write" ON public.articles;
CREATE POLICY "articles_owner_write"
    ON public.articles FOR ALL
    USING (auth.uid() = author_id)
    WITH CHECK (auth.uid() = author_id);

-- 🔑 admin은 모든 기사 접근 가능 (members.role = 'admin')
DROP POLICY IF EXISTS "articles_admin_all" ON public.articles;
CREATE POLICY "articles_admin_all"
    ON public.articles FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.members
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- article_media: 연결된 기사 작성자 or admin
DROP POLICY IF EXISTS "media_public_read" ON public.article_media;
CREATE POLICY "media_public_read"
    ON public.article_media FOR SELECT USING (true);

DROP POLICY IF EXISTS "media_owner_write" ON public.article_media;
CREATE POLICY "media_owner_write"
    ON public.article_media FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.articles a
            WHERE a.id = article_id AND a.author_id = auth.uid()
        )
    );

-- article_related: 동일 규칙
DROP POLICY IF EXISTS "related_public_read" ON public.article_related;
CREATE POLICY "related_public_read"
    ON public.article_related FOR SELECT USING (true);

DROP POLICY IF EXISTS "related_owner_write" ON public.article_related;
CREATE POLICY "related_owner_write"
    ON public.article_related FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.articles a
            WHERE a.id = article_id AND a.author_id = auth.uid()
        )
    );

-- ── rep_media_id FK 추가 (article_media 생성 후) ────────────
ALTER TABLE public.articles
    ADD CONSTRAINT fk_rep_media
    FOREIGN KEY (rep_media_id)
    REFERENCES public.article_media(id)
    ON DELETE SET NULL
    DEFERRABLE INITIALLY DEFERRED;

-- ── 완료 확인 ────────────────────────────────────────────────
SELECT
    table_name,
    (SELECT COUNT(*) FROM information_schema.columns c WHERE c.table_name = t.table_name AND c.table_schema = 'public') AS col_count
FROM information_schema.tables t
WHERE t.table_schema = 'public'
  AND t.table_name IN ('articles', 'article_media', 'article_related')
ORDER BY t.table_name;
