-- [공실뉴스 지도 서비스를 위한 테이블 생성 SQL]
-- Supabase 대시보드 -> SQL Editor -> New Query 에 붙여넣고 Run 해주세요.

-- 1. news 테이블 생성
create table if not exists public.news (
    id bigint generated by default as identity primary key,
    title text not null,
    link text not null unique,
    description text,
    author text,
    pub_date timestamptz,
    image_url text,
    lat float8,
    lng float8,
    source text default 'gongsilnews',
    created_at timestamptz default now()
);

-- 2. 검색 및 지도 조회를 위한 인덱스 생성
create index if not exists news_link_idx on public.news (link);
create index if not exists news_geo_idx on public.news (lat, lng);
create index if not exists news_pub_date_idx on public.news (pub_date desc);

-- 3. 권한 설정 (중요: 공개 키로 저장할 수 있도록 허용)
alter table public.news enable row level security;

-- 기존 정책 제거 (재실행 시 에러 방지)
drop policy if exists "Allow all access" on public.news;

-- 모든 사용자에게 읽기/쓰기 허용 정책 추가
create policy "Allow all access"
on public.news
for all
using (true)
with check (true);

-- 4. members 테이블 생성 및 관리 (회원 구분 및 등급 관리)
create table if not exists public.members (
    id uuid primary key,
    email text not null unique,
    role text default 'general',
    membership text default 'free',
    member_num bigint generated always as identity,
    expired_at timestamptz,
    created_at timestamptz default now()
);

-- 인덱스 및 RLS 설정
create index if not exists members_email_idx on public.members (email);
alter table public.members enable row level security;

drop policy if exists "Allow all access" on public.members;
create policy "Allow all access"
on public.members
for all
using (true)
with check (true);
